# Generated by Django 5.2.8 on 2025-11-10 16:14

from django.db import migrations

def migrate_author_to_contributors(apps, schema_editor):
    Blog = apps.get_model('blog', 'Blog')
    for blog in Blog.objects.all():
        if blog.author:
            blog.contributors.add(
                blog.author, through_defaults={'contribution': 'Auteur principal'})


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_author_alter_blog_contributors'),
    ]

    operations = [
        migrations.RunPython(migrate_author_to_contributors),
    ]
