# Generated by Django 5.2.8 on 2025-11-10 13:53

from django.db import migrations


def create_groups(apps, schema_migration):
    # Récupère le modèle User défini dans l’application 'authentication'
    User = apps.get_model('authentication', 'User')
    
    # Récupère les modèles Group et Permission fournis par Django (dans 'auth')
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')

    # Récupère les permissions liées au modèle Photo (ajouter, modifier, supprimer, voir)
    add_photo = Permission.objects.get(codename='add_photo')       # permission d'ajouter une photo
    change_photo = Permission.objects.get(codename='change_photo') # permission de modifier une photo
    delete_photo = Permission.objects.get(codename='delete_photo') # permission de supprimer une photo
    view_photo = Permission.objects.get(codename='view_photo')     # permission de voir une photo

    # Regroupe toutes les permissions du créateur (creator)
    creator_permissions = [
        add_photo,
        change_photo,
        delete_photo,
        view_photo,
    ]
    
    # Crée un groupe "creators" (pour les utilisateurs qui peuvent gérer les photos)
    creators = Group(name='creators')
    creators.save()  # Enregistre le groupe dans la base de données
    
    # Associe au groupe "creators" toutes les permissions de création/modification/suppression/visualisation
    creators.permissions.set(creator_permissions)

    # Crée un groupe "subscribers" (utilisateurs qui peuvent seulement voir les photos)
    subscribers = Group(name='subscribers')
    subscribers.save()  # Enregistre le groupe dans la base de données
    
    # Donne uniquement la permission de visualisation aux "subscribers"
    subscribers.permissions.add(view_photo)
    
    # Parcourt tous les utilisateurs existants pour les ajouter au bon groupe selon leur rôle
    for user in User.objects.all():
        if user.role == 'CREATOR':
            # Ajoute l’utilisateur dans le groupe "creators" s’il a le rôle CREATOR
            creators.user_set.add(user)
        if user.role == 'SUBSCRIBER':
            # Ajoute l’utilisateur dans le groupe "subscribers" s’il a le rôle SUBSCRIBER
            subscribers.user_set.add(user)




class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
