# Generated by Django 5.2.8 on 2025-11-10 14:24

from django.db import migrations

def assign_blog_permissions(apps, schema_migration):
    # Récupère le modèle Group de l'application auth
    Group = apps.get_model('auth', 'Group')
    
    # Récupère le modèle Permission de l'application auth
    Permission = apps.get_model('auth', 'Permission')

    # Récupère les permissions liées au modèle Blog
    add_blog = Permission.objects.get(codename='add_blog')       # permission pour ajouter un blog
    change_blog = Permission.objects.get(codename='change_blog') # permission pour modifier un blog
    delete_blog = Permission.objects.get(codename='delete_blog') # permission pour supprimer un blog
    view_blog = Permission.objects.get(codename='view_blog')     # permission pour voir un blog

    # Récupère le groupe "creators" (créateurs)
    creators = Group.objects.get(name='creators')
    
    # Assigne toutes les permissions du blog au groupe "creators"
    creators.permissions.add(add_blog)      # permission d'ajouter un blog
    creators.permissions.add(change_blog)   # permission de modifier un blog
    creators.permissions.add(delete_blog)   # permission de supprimer un blog
    creators.permissions.add(view_blog)     # permission de voir un blog

    # Récupère le groupe "subscribers" (abonnés)
    subscribers = Group.objects.get(name='subscribers')
    
    # Donne uniquement la permission de voir le blog au groupe "subscribers"
    subscribers.permissions.add(view_blog)


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20251110_1353'),
    ]

    operations = [
        migrations.RunPython(assign_blog_permissions)
    ]
